###############################################################################
#                            Based on phpdocker.io                            #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        container_name: applifting-test-redis
        networks:
            - 'applifting-test-net'

    postgres:
        image: 'postgres:12.5-alpine'
        container_name: applifting-test-postgres
        working_dir: /application
        volumes:
            - './application:/application'
            - './postgres:/var/lib/postgresql'
        environment:
            - POSTGRES_USER=applifting-test
            - POSTGRES_PASSWORD=donotremindmeanythingsafeforsicknamingwhenisearchforthat
            - POSTGRES_DB=applifting-test-app
            - POSTGRES_PASS=donotremindmeanythingsafeforsicknamingwhenisearchforthat
            - POSTGRES_DBNAME=applifting-test
        ports:
            - '65432:5432'
        networks:
            - 'applifting-test-net'

    webserver:
        restart: always
        build: phpdocker/nginx
        container_name: applifting-test-web
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '23459:89'
        networks:
            - 'applifting-test-net'

    php-adminer:
        build: phpdocker/php-fpm7
        container_name: applifting-test-adminer
        working_dir: /application
        volumes:
            - './adminer:/application'
            - './phpdocker/php-fpm7/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
        networks:
            - 'applifting-test-net'

    python-app:
        build: phpdocker/python3
        container_name: applifting-test-app
        working_dir: /application
        stop_signal: SIGINT
        volumes:
            - './application:/application'
            - '/var/run/docker.sock:/var/run/docker.sock'
        ports:
            - '23450:80'
        environment:
            - APP_PORT=23456
            - DB_HOST=applifting-test-postgres
            - DB_USER=applifting-test
            - DB_PASS=donotremindmeanythingsafeforsicknamingwhenisearchforthat
            - DB_NAME=applifting-test-app
            - REDIS_HOST=applifting-test-redis
            - MASTER_KEY=040db080fdef619f68b204f8d7321654
            - MASTER_TOKEN=56nhj456fhj456m4g6h4k53mj
        command: 'python3 /application/app.py'
        networks:
            - 'applifting-test-net'

networks:
    applifting-test-net:
        driver: bridge
